on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - uses: actions/checkout@v4
      with:
         path: './src/github.com/segmentio/conf'
    - run: echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/segmentio/conf'
